-- =====================================================================
-- L1 (silver) — SAP_BDC_L1 curated passthrough views over the L0
-- SAP BDC data products (zero-copy BDC Connect shares).
-- =====================================================================

create database if not exists SAP_WORKING_CAPITAL_360;
create or replace schema SAP_WORKING_CAPITAL_360.SAP_BDC_L1;

-- Entry View Journal Entry: operational open items (AR + AP lines)
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.OPERATIONAL_ACCTG_DOC_ITEM as
select * from SAP_BDC_DEMO_ENTRY_VIEW_JOURNAL_ENTRY.BDCCONNECT.OPERATIONALACCTGDOCITEM;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.OPERATIONAL_ACCTG_CLEARING_HISTORY as
select * from SAP_BDC_DEMO_ENTRY_VIEW_JOURNAL_ENTRY.BDCCONNECT.OPLACCTGDOCITEMCLEARINGHISTORY;

-- Accounts payable
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.SUPPLIER_INVOICE as
select * from SAP_BDC_DEMO_SUPPLIER_INVOICE.BDCCONNECT.SUPPLIERINVOICE;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.PAYMENT_TERMS as
select * from SAP_BDC_DEMO_PAYMENT_TERMS.BDCCONNECT.PAYMENTTERMS;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.PAYMENT_TERMS_CONDITIONS as
select * from SAP_BDC_DEMO_PAYMENT_TERMS.BDCCONNECT.PAYMENTTERMSCONDITIONS;

-- Accounts receivable / collections
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.BILLING_DOCUMENT as
select * from SAP_BDC_DEMO_BILLING_DOCUMENT.BDCCONNECT.BILLINGDOCUMENT;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.COLLECTIONS_WORKLIST_ITEM as
select * from SAP_BDC_DEMO_COLLECTIONS_WORKLIST_ITEM.BDCCONNECT.COLLECTIONSWORKLISTITEM;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.DISPUTE_CASE as
select * from SAP_BDC_DEMO_DISPUTE_CASE.BDCCONNECT.DISPUTECASE;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.PROMISE_TO_PAY as
select * from SAP_BDC_DEMO_PROMISE_TO_PAY.BDCCONNECT.PROMISETOPAY;

-- Cash & liquidity
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.CASH_FLOW as
select * from SAP_BDC_DEMO_CASH_FLOW.BDCCONNECT.CASHFLOW;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.CASH_FLOW_FORECAST as
select * from SAP_BDC_DEMO_CASH_FLOW.BDCCONNECT.CASHFLOWFORECAST;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.BANK_ACCOUNT as
select * from SAP_BDC_DEMO_BANK_ACCOUNT.BDCCONNECT.BANKACCOUNT;
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.HOUSE_BANK as
select * from SAP_BDC_DEMO_HOUSE_BANK.BDCCONNECT.HOUSEBANK;

-- Inventory
create or replace view SAP_WORKING_CAPITAL_360.SAP_BDC_L1.PHYSICAL_INVENTORY_DOCUMENT_ITEM as
select * from SAP_BDC_DEMO_PHYSICAL_INVENTORY_DOCUMENT.BDCCONNECT.PHYSICALINVENTORYDOCUMENTITEM;
